name: Run dagger examples
on:
  pull_request: 
    
jobs:
  examples:
    name: Run examples 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      
      - name: Run
        uses: dagger/dagger-for-github@847ae4458ef34fe9b5f566655957bde6d4891112
        with:
          version: "latest"
          verb: call
          module: ./tests
          args: all
